### ISSUE TITLE
Add license information to readme + contributing file

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-os-example-devicekey#39]
Sufficient to follow what blinky has or other examples, see https://github.com/ARMmbed/mbed-os-example-kvstore#license-and-contributions

**Comment by 0xc0170** [comment]
https://github.com/ARMmbed/mbed-os-example-tls/pull/241

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTSTOR-998*
