### ISSUE TITLE
DeviceKey Root of Trust not generated

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-devicekey#71]
### Description of defect

When running this example on a board with TRNG, and if the board's flash doesn't contain a Root of Trust already, the example fails:
```
--- Error, derive key failed with error code -5 ---
```

This is because the generation of Root of Trust is missing. Since https://github.com/ARMmbed/mbed-os/pull/12385 was merged, the Root of Trust is not automatically generated anymore.

#### Target(s) affected by this defect ?

Any target with TRNG (e.g. DISCO_L475VG_IOT01A)

#### Toolchain(s) (name and version) displaying this defect ?

Any

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.9.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

Any

#### How is this defect reproduced ?

Erase any existing DeviceKey Root of Trust (if any), then build and run this example on a DISCO_L475VG_IOT01A board (for example).

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3821*

**Comment by LDong-Arm** [comment]
Fixes:
* Example: #72
* Documentation update: https://github.com/ARMmbed/mbed-os/pull/14550

**Comment by Patater** [comment]
Fixed by https://github.com/ARMmbed/mbed-os-example-devicekey/pull/72
